### PR TITLE
Fix linux path problem & Trying to fix https://github.com/CosmosOS/Cosmos/issues/3046

### PR DESCRIPTION
**Pull request by gamma63**

### CODE REVIEW

**Comment by gamma63** [comment]
napoleon-there-is-nothing-we-can-do-2206763917
I am tried everything, but I guess it's either the csproj file or something wrong with COSMOS itself.

**Comment by Vardan2009** [comment]
Maybe you can try creating a new empty cosmos project on your machine and then copy the source files?

**Comment by gamma63** [comment]
> Maybe you can try creating a new empty cosmos project on your machine and then copy the source files?

image
Yeah the problem is with COSMOS itself
Or whatever this plug is
image
 :-(

**Comment by Vardan2009** [comment]
Interesting... you can try opening an issue in the Cosmos repository.

**Comment by gamma63** [comment]
Okay

**Pull request closed without merging**
